language: ruby
rvm:
- 2.2.2
sudo: false
cache: bundler
script:
- bundle exec rails server &
- bundle exec rake ci
- bundle exec rubocop -D
env:
  global:
  - secure: wwyb5IUpAkydU6eQbgVJ/+oshedAOdiCARMYvhC14zBlie8FvQrY3kGINSQ1jWNGcz3Gbo23VNLXSSUjk9jbuO4SSri1w28xvoe3Wjqz+r0+zWETRKh3mZ83PxAu7x0565cfNwdGaw788Wvvo34/Bl5j18zEinn6UL9ICBW6UDg=
  - secure: JqYu9MWtYlV6u+gjl7DthI7MKyLoLANYMhSM11hWgyQsZcXIanYTmBsdpvKC0GPXUmfy4TvwQMKYrixxoSW65W+4P8FwU7e4TirjLV1FDl1zFiBT/L1wyl+8qmW9Ot9b68Q0phXH0UhG31Qif4na+dhdrHRvPUgowh8/NawIJwg=
