# Case-insensitive substring on the left,
# replacement on the right.
# Final line is a fall-through.

!omap
  Album: Album
  Clip: Clip
  Compilation: Compilation
  Element: Raw Footage
  B-roll: Raw Footage
  broll: Raw Footage
  Field Tape: Raw Footage
  News Conference: Raw Footage
  NEWS RELEASE: Raw Footage
  News Tape: Raw Footage
  Original footage: Raw Footage
  Original recording: Raw Footage
  Outtake: Raw Footage
  Raw Footage: Raw Footage
  Stock Footage: Raw Footage
  Stock shot: Raw Footage
  unedited footage: Raw Footage
  Episode: Episode
  Program: Program
  Porgram: Program
  Television special: Program
  Promo: Promo
  Advertis: Promo
  Commercial Spots: Promo
  PSA: Promo
  Public Announcement: Promo
  Trailer: Promo
  Segment: Segment
  Segrment: Segment
  Track: Track
  epi: Episode
  '': ''
