---
- state: Kansas
  abbreviation: KS
  blurb_fill:
    naeb_station: U. of Kansas
  blurb_md: &naeb_blurb >
    [Additional audio content from %{naeb_station} in %{state}]
    (/catalog?&f[access_types][]=all&q="%{naeb_station}")
    is part of the National Association of Educational Broadcasters (NAEB) collection,
    contributed by the University of Maryland to the AAPB.

    The NAEB was established in 1934 from a precursor organization that formed in 1925.
    In 1951, NAEB established a tape duplication exchange system in Urbana, IL, where
    programs produced by university radio stations across the country were copied and
    distributed to member stations, an early networking scheme that influenced the
    history of later public radio and television systems. The more than 5,500 NAEB
    programs available in the AAPB come from the 1950s and 1960s, and include radio
    documentaries, coverage of events (hearings, meetings, conferences, and seminars),
    interviews, debates, and lectures on public affairs topics such as civil rights,
    foreign affairs, health, politics, education, and broadcasting.

- state: South Dakota
  blurb_fill:
    naeb_station: KFJM
  blurb_md: *naeb_blurb
  abbreviation: SD

- state: North Dakota
  blurb_fill:
    naeb_station: KUSD
  blurb_md: *naeb_blurb
  abbreviation: ND

- state: Alabama
  blurb_fill:
    naeb_station: WUOA
  blurb_md: *naeb_blurb
  abbreviation: AL

- state: Alaska
  abbreviation: AK

- state: Arizona
  abbreviation: AZ

- state: Arkansas
  abbreviation: AR

- state: California
  blurb_fill:
    naeb_station:
  blurb_md: >
    Additional audio content from [KPPC](/catalog?f[access_types][]=all&q=kppc), [KEBS](/catalog?utf8=✓&f[access_types][]=all&f[organization][]=University of Maryland (MD)&q=kebs), and [San Bernardino Valley College](/catalog?utf8=✓&f[access_types][]=all&f[organization][]=University of Maryland (MD)&q="San Bernardino Valley") in California is part of the National Association of Educational Broadcasters (NAEB) collection,
    contributed by the University of Maryland to the AAPB.

    The NAEB was established in 1934 from a precursor organization that formed in 1925.
    In 1951, NAEB established a tape duplication exchange system in Urbana, IL, where
    programs produced by university radio stations across the country were copied and
    distributed to member stations, an early networking scheme that influenced the
    history of later public radio and television systems. The more than 5,500 NAEB
    programs available in the AAPB come from the 1950s and 1960s, and include radio
    documentaries, coverage of events (hearings, meetings, conferences, and seminars),
    interviews, debates, and lectures on public affairs topics such as civil rights,
    foreign affairs, health, politics, education, and broadcasting.
  abbreviation: CA

- state: Colorado
  blurb_fill:
    naeb_station: University of Denver
  blurb_md: *naeb_blurb
  abbreviation: CO

- state: Connecticut
  abbreviation: CT

- state: Delaware
  abbreviation: DE

- state: Florida
  blurb_fill:
    naeb_station: University of Florida
  blurb_md: *naeb_blurb
  abbreviation: FL

- state: Georgia
  abbreviation: GA

- state: Hawaii
  abbreviation: HI

- state: Idaho
  abbreviation: ID

- state: Illinois
  blurb_fill:
    naeb_station:
  blurb_md: >
    Additional audio content from [University of Chicago](/catalog?utf8=✓&f[access_types][]=all&f[organization][]=University of Maryland (MD)&q="u. of chicago") and [WMBI](/catalog?utf8=✓&f[access_types][]=all&f[organization][]=University of Maryland (MD)&q=wmbi) in Illinois is part of the National Association of Educational Broadcasters (NAEB) collection,
    contributed by the University of Maryland to the AAPB.

    The NAEB was established in 1934 from a precursor organization that formed in 1925.
    In 1951, NAEB established a tape duplication exchange system in Urbana, IL, where
    programs produced by university radio stations across the country were copied and
    distributed to member stations, an early networking scheme that influenced the
    history of later public radio and television systems. The more than 5,500 NAEB
    programs available in the AAPB come from the 1950s and 1960s, and include radio
    documentaries, coverage of events (hearings, meetings, conferences, and seminars),
    interviews, debates, and lectures on public affairs topics such as civil rights,
    foreign affairs, health, politics, education, and broadcasting.
  abbreviation: IL

- state: Indiana
  blurb_fill:
    naeb_station: WBAA
  blurb_md: *naeb_blurb
  abbreviation: IN

- state: Iowa
  blurb_fill:
    naeb_station: WSUI
  blurb_md: *naeb_blurb
  abbreviation: IA

- state: Kentucky
  abbreviation: KY

- state: Louisiana
  abbreviation: LA

- state: Maine
  abbreviation: ME

- state: Maryland
  abbreviation: MD

- state: Massachusetts
  abbreviation: MA

- state: Michigan
  blurb_fill:
    naeb_station:
  blurb_md: >
    Additional audio content from [WUOM](/catalog?utf8=✓&f[access_types][]=all&q=wuom), [WDET](/catalog?f[access_types][]=all&f[organization][]=University of Maryland (MD)&q=wdet), and [WMUK](/catalog?f[access_types][]=all&f[organization][]=University of Maryland (MD)&q=wmuk) in Michigan is part of the National Association of Educational Broadcasters (NAEB) collection,
    contributed by the University of Maryland to the AAPB.

    The NAEB was established in 1934 from a precursor organization that formed in 1925.
    In 1951, NAEB established a tape duplication exchange system in Urbana, IL, where
    programs produced by university radio stations across the country were copied and
    distributed to member stations, an early networking scheme that influenced the
    history of later public radio and television systems. The more than 5,500 NAEB
    programs available in the AAPB come from the 1950s and 1960s, and include radio
    documentaries, coverage of events (hearings, meetings, conferences, and seminars),
    interviews, debates, and lectures on public affairs topics such as civil rights,
    foreign affairs, health, politics, education, and broadcasting.
  abbreviation: MI

- state: Minnesota
  abbreviation: MN

- state: Mississippi
  abbreviation: MS

- state: Missouri
  abbreviation: MO

- state: Montana
  abbreviation: MT

- state: Nebraska
  abbreviation: NE

- state: Nevada
  abbreviation: NV

- state: New Hampshire
  abbreviation: NH

- state: New Jersey
  abbreviation: NJ

- state: New Mexico
  abbreviation: NM

- state: New York
  blurb_fill:
    naeb_station:
  blurb_md: >
    Additional audio content from [WRVR](/catalog?utf8=✓&f[access_types][]=all&f[organization][]=University of Maryland (MD)&q=wrvr), [Union Theological Seminary](/catalog?utf8=✓&f[access_types][]=all&f[organization][]=University of Maryland (MD)&q="union theological seminary"), and [WBFO] (/catalog?utf8=✓&f[access_types][]=all&f[organization][]=University of Maryland (MD)&q=wbfo) in New York is part of the National Association of Educational Broadcasters (NAEB) collection,
    contributed by the University of Maryland to the AAPB.

    The NAEB was established in 1934 from a precursor organization that formed in 1925.
    In 1951, NAEB established a tape duplication exchange system in Urbana, IL, where
    programs produced by university radio stations across the country were copied and
    distributed to member stations, an early networking scheme that influenced the
    history of later public radio and television systems. The more than 5,500 NAEB
    programs available in the AAPB come from the 1950s and 1960s, and include radio
    documentaries, coverage of events (hearings, meetings, conferences, and seminars),
    interviews, debates, and lectures on public affairs topics such as civil rights,
    foreign affairs, health, politics, education, and broadcasting.
  abbreviation: NY

- state: North Carolina
  abbreviation: NC

- state: Ohio
  blurb_fill:
    naeb_station: WMUB
  blurb_md: >
    Additional audio content from [WMUB](/catalog?utf8=✓&f[access_types][]=all&f[organization][]=University of Maryland (MD)&q=wmub) and [WGUC](/catalog?utf8=✓&f[access_types][]=all&f[organization][]=University of Maryland (MD)&q=wguc) in Ohio is part of the National Association of Educational Broadcasters (NAEB) collection,
    contributed by the University of Maryland to the AAPB.

    The NAEB was established in 1934 from a precursor organization that formed in 1925.
    In 1951, NAEB established a tape duplication exchange system in Urbana, IL, where
    programs produced by university radio stations across the country were copied and
    distributed to member stations, an early networking scheme that influenced the
    history of later public radio and television systems. The more than 5,500 NAEB
    programs available in the AAPB come from the 1950s and 1960s, and include radio
    documentaries, coverage of events (hearings, meetings, conferences, and seminars),
    interviews, debates, and lectures on public affairs topics such as civil rights,
    foreign affairs, health, politics, education, and broadcasting.
  abbreviation: OH

- state: Oklahoma
  abbreviation: OK

- state: Oregon
  abbreviation: OR

- state: Pennsylvania
  blurb_fill:
    naeb_station: WDUQ
  blurb_md: *naeb_blurb
  abbreviation: PA

- state: Rhode Island
  abbreviation: RI

- state: South Carolina
  abbreviation: SC

- state: Tennessee
  abbreviation: TN

- state: Texas
  abbreviation: TX

- state: Utah
  abbreviation: UT

- state: Vermont
  abbreviation: VT

- state: Virginia
  abbreviation: VA

- state: Washington
  blurb_fill:
    naeb_station: KWSC
  blurb_md: *naeb_blurb
  abbreviation: WA

- state: West Virginia
  abbreviation: WV

- state: Wisconsin
  abbreviation: WI

- state: Wyoming
  abbreviation: WY

- state: DC
  blurb_fill:
    naeb_station: Georgetown Forum
  blurb_md: *naeb_blurb
  abbreviation: DC

- state: Guam
  abbreviation: GU

- state: Washington, DC
  abbreviation: DC
