# Quotes are optional, unless the string contains colons.
# If the image is sitting in the expected place on the media server,
# "thumbnail_url" can be omitted.

- id: cpb-aacip_16-322bvw0h
  org_name: WILL Illinois Public Media
  name: "Access to Life: Perspectives on the Americans with Disabilities Act"

- id: cpb-aacip_17-68kd607x
  org_name: Louisiana Public Broadcasting
  name: "Jolie Louisiane"

- id: cpb-aacip_41-34fn32k9
  org_name: South Carolina ETV
  name: "Carolina Journal: State Fair Open"

- id: cpb-aacip_78-88qc0bgv
  org_name: ideastream
  name: "Cuyahoga Valley Scenic Railroad Interviews"

- id: cpb-aacip_85-816m97b2
  org_name: WBRA
  name: "The Civil War Series"

- id: cpb-aacip_160-504xh3r1
  org_name: WTIU
  name: "Artists for America Birthday Party"

- id: cpb-aacip_200-90rr571f
  org_name: WFYI
  name: "Across Indiana"

- id: cpb-aacip_283-708w9sc7
  org_name: KCTS 9
  name: "Pacific Northwest Ballet"

- id: cpb-aacip_296-23hx3hkp
  org_name: Northwest Public Television
  name: "South by Northwest"

- id: cpb-aacip_402-676t1pf9
  org_name: KUT
  name: "City Council Proclamation for KUT"
  thumbnail_url: /thumbs/audio-digitized.jpg

- id: cpb-aacip_43-9351cpg7
  org_name: Minnesota Public Radio
  name: "Midday: A Celebration of Citizenship"
  thumbnail_url: /thumbs/audio-digitized.jpg

- id: cpb-aacip_301-623bk926
  org_name: WERU
  name: "Hit the Dirt: Breaking New Ground"
  thumbnail_url: /thumbs/audio-digitized.jpg

- id: cpb-aacip_138-881jx2hv
  org_name: Appalshop
  name: "Mountain News & World Report"
  thumbnail_url: /thumbs/audio-digitized.jpg

- id: cpb-aacip_215-085hqd1g
  org_name: WHYY
  name: "Radio Times with Marty Moss-Coane"
  thumbnail_url: /thumbs/audio-digitized.jpg

- id: cpb-aacip_83-98z8ws88
  org_name: KUED
  name: "Jackson Hole Story"

- id: cpb-aacip_328-26xwdfkn
  org_name: Idaho Public Television
  name: "Idaho Reports: Peaceful Settlements"

- id: cpb-aacip_75-676t1r2p
  org_name: Thirteen WNET
  name: "The Smallest TV Station in the World"

- id: cpb-aacip_204-45q83ghs
  org_name: KWSO
  name: "Our People & Mother Earth"
  thumbnail_url: /thumbs/audio-digitized.jpg

- id: cpb-aacip_187-472v74d4
  org_name: New Hampshire Public Radio
  name: "New Hampshire Folk Festival"
  thumbnail_url: /thumbs/audio-digitized.jpg

- id: cpb-aacip_217-22h70wc4
  org_name: WKAR
  name: "Evening with the Governor"

- id: cpb-aacip_293-09j3tz4m
  org_name: WHUT
  name: "At Howard: Julian Bond"

- id: cpb-aacip_50-8279czcb
  org_name: WBEZ
  name: "Chicago Blues Festival"
  thumbnail_url: /thumbs/audio-digitized.jpg

- id: cpb-aacip_129-67wm3jgd
  org_name: UNC-TV
  name: "North Carolina Now"

- id: cpb-aacip_259-d7959g55
  org_name: New Jersey Network
  name: "New Jersey Nightly News"

- id: cpb-aacip_423-70zpcg95
  org_name: KUVO
  name: "Diane Reeves Live at KUVO"
  thumbnail_url: /thumbs/audio-digitized.jpg

- id: cpb-aacip_394-558czmhs
  org_name: Maryland Public Television
  name: "Outdoors Maryland"

- id: cpb-aacip_120-23612q7j
  org_name: WQED
  name: "OnQ"

- id: cpb-aacip_77-848pm62r
  org_name: Twin Cities Public Television
  name: "Nighttimes Variety"

- id: cpb-aacip_384-72b8h347
  org_name: KCPT
  name: "Kansas Governor's Debate"

- id: cpb-aacip_322-50tqjvg2
  org_name: WEDU
  name: "Interview with Neil deGrasse Tyson"

- id: cpb-aacip_27-300zpg0r
  org_name: WYSO
  name: "Old Time Women: A Grandmother's Day Special"
  thumbnail_url: /thumbs/audio-digitized.jpg

- id: cpb-aacip_426-40xpp0m4
  org_name: KEET
  name: "Pawns of Paradise"

- id: cpb-aacip_24-h707w67g4g
  org_name: KEXP
  name: "Live Room: Modest Mouse"
  thumbnail_url: /thumbs/audio-digitized.jpg

- id: cpb-aacip_359-00ns1w0w
  org_name: KET - Kentucky Educational Television
  name: "Bobbie Ann Mason Interview and Reading"

- id: cpb-aacip_88-23vt4dfp
  org_name: KRCB
  name: "En Camino: Latino Artists"

- id: cpb-aacip_362-47dr7zcn
  org_name: WFMU
  name: "Ladysmith Black Mambazo, 1987"
  thumbnail_url: /thumbs/audio-digitized.jpg

- id: cpb-aacip_81-32d7wr60
  org_name: WNED
  name: "Woman: Simone De Beauvoir"

- id: cpb-aacip_331-010p2nnm
  org_name: WTIP
  name: "Northern Gardening"
  thumbnail_url: /thumbs/audio-digitized.jpg

- id: cpb-aacip_333-17qnkc0k
  org_name: PBS Guam
  name: "Guam A La Mode"
